config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
get 'fashions/fashion' => 'fashions#fashion'
get 'fashions/word' => 'fashions#word'
get 'fashions/news' => 'fashions#news'
get 'fashions/food' => 'fashions#food'
get 'fashions/music' => 'fashions#music'
get 'fashions/movie' => 'fashions#movie'
get 'fashions/things' => 'fashions#things'
get 'fashions/others' => 'fashions#others'
get 'users/index' => 'users#index'


resources :fashions do
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create]
end
root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :fashion
end

app/models/fashion.rb
class Fashion < ApplicationRecord

    mount_uploader :image, ImageUploader
    belongs_to :user 
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :fashion
  belongs_to :user

  validates_uniqueness_of :fashion_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :fashions, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_fashions, through: :likes, source: :fashion
  has_many :comments, dependent: :destroy

  def already_liked?(fashion)
    self.likes.exists?(fashion_id: fashion.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
        before_action :authenticate_user!
      
        def create
          fashion = Fashion.find(params[:fashion_id])
          comment = fashion.comments.build(comment_params)
          comment.user_id = current_user.id
          if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path) 
          else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path) 
          end
        end
      
        private
      
          def comment_params
            params.require(:comment).permit(:content)
          end
end

app/controllers/fashions_controller.rb
class FashionsController < ApplicationController
  before_action :authenticate_user!
     def new
        @fashion = Fashion.new
      end
    
      def index
         @fashion = Fashion.all
      end

      def create
        fashion = Fashion.new(fashion_params)

        fashion.user_id = current_user.id 

        if fashion.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def fashion
        @fashion = Fashion.all
      end
    
      def word
        @fashion = Fashion.all
      end
    
      def news
        @fashion = Fashion.all
      end

      def food
        @fashion = Fashion.all
      end

      def music
        @fashion = Fashion.all
      end

      def movie
        @fashion = Fashion.all
      end

      def things
        @fashion = Fashion.all
      end

      def others
        @fashion = Fashion.all
      end

      def show
        @fashion = Fashion.find(params[:id])
        @comments = @fashion.comments
        @comment = Comment.new
      end

      def edit
        @fashion = Fashion.find(params[:id])
      end

      def update
        fashion = Fashion.find(params[:id])
        if fashion.update(fashion_params)
          redirect_to :action => "show", :id => fashion.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        fashion = Fashion.find(params[:id])
        fashion.destroy
        redirect_to action: :index
      end
     
      private
      def fashion_params
        params.require(:fashion).permit(:title, :genre, :about, :image, :category)
      end
    
    end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(fashion_id: params[:fashion_id]) 
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(fashion_id: params[:fashion_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fashions_helper.rb
module FashionsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fashions/edit.html.erb
<%= form_for @fashion do |f| %>
    <%= f.label :body %>
    <%= f.text_field :about, :size => 140 %>
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <%= f.submit "編集する" %>
  <% end %>

app/views/fashions/fashion.html.erb
<h1>FASHION</h1>
<% @fashion.each do |t| %>
    <% if t.genre == "fashion" %>  
    <p>タイトル:<%= t.title %></p>
    <p>ジャンル:<%= t.genre %></p>
    <p>内容:<%= t.about %></p>
    <p>画像:<%= image_tag t.image_url, size: "250x200" if t.image? %></p>
    <p>投稿日:<%= t.created_at %></p>

    <% end %>
  <% end %>

  <%= link_to "一覧に戻る", fashions_path %>

app/views/fashions/food.html.erb
<h1>FOOD</h1>
<% @fashion.each do |t| %>
    <% if t.genre == "food" %>  
    <p>タイトル:<%= t.title %></p>
    <p>ジャンル:<%= t.genre %></p>
    <p>内容:<%= t.about %></p>
    <p>画像:<%= image_tag t.image_url, size: "250x200" if t.image? %></p>
    <p>投稿日:<%= t.created_at %></p>
    <% end %>
  <% end %>

  <%= link_to "一覧に戻る", fashions_path %>

app/views/fashions/index.html.erb
<h1>Now Trend</h1>
<h3>一覧ページ</h3>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<%= link_to "新規投稿へ", new_fashion_path %>
<%= link_to "ファッション", "/fashions/fashion" %>
<%= link_to "ワード", "/fashions/word" %>
<%= link_to "ニュース", "/fashions/news" %>
<%= link_to "フード", "/fashions/food" %>
<%= link_to "ミュージック", "/fashions/music" %>
<%= link_to "ムービー・TV", "/fashions/movie" %>
<%= link_to "モノ", "/fashions/things" %>
<%= link_to "その他", "/fashions/others" %>

<div class="fashions-container">
  <% @fashion.each do |t| %>
    <div class="fashion">
      <%= t.user.email %>
      <%= t.title %>
      <%= t.genre %>
      <%= t.about %>
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= link_to fashion_like_path(id: t.id, fashion_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% else %>
          <%= link_to fashion_likes_path(id: t.id, fashion_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% end %>
      <% else %>
        <i class="far fa-heart"></i><%= t.likes.count %>
      <% end %>
      <%= t.created_at %>
      <%= link_to "詳細へ", fashion_path(t.id) %>
      <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_fashion_path(t.id) %>
      <%= link_to "削除する", fashion_path(t.id), method: :delete %>
       <% end %> 
    </div>
  <% end %>
</div>

app/views/fashions/movie.html.erb
<h1>MOVIE・TV</h1>
<% @fashion.each do |t| %>
    <% if t.genre == "movie" %>  
    <p>タイトル:<%= t.title %></p>
    <p>ジャンル:<%= t.genre %></p>
    <p>内容:<%= t.about %></p>
    <p>画像:<%= image_tag t.image_url, size: "250x200" if t.image? %></p>
    <p>投稿日:<%= t.created_at %></p>
    <% end %>
  <% end %>

  <%= link_to "一覧に戻る", fashions_path %>

app/views/fashions/music.html.erb
<h1>MUSIC</h1>
<% @fashion.each do |t| %>
    <% if t.genre == "music" %> 
    <p>タイトル:<%= t.title %></p>
    <p>ジャンル:<%= t.genre %></p>
    <p>内容:<%= t.about %></p>
    <p>画像:<%= image_tag t.image_url, size: "250x200" if t.image? %></p>
    <p>投稿日:<%= t.created_at %></p>
    
    

    <% end %>
  <% end %>

  <%= link_to "一覧に戻る", fashions_path %>

app/views/fashions/new.html.erb
<h1>Now Trend</h1>
<h3>新規投稿ページ</h3>
<%= form_for @fashion do |f| %>

  <div class="field">
    <%= f.label :Title %>
    <%= f.text_field :title, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :Genre  %>
    <%= f.select :genre, 
    [["fashion", "fashion"], 
    ["word", "word"], 
    ["news", "news"],
    ["food", "food"],
    ["music", "music"],
    ["movie・TV", "movie・TV"],
    ["things", "things"],
    ["others", "others"]], include_blank: "選択して下さい" %>
  </div>


  <div class="field">
    <%= f.label:本文 %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :Phot %>
    <%= f.file_field :image %>
  </div>



  <%= f.submit "投稿する" %>


<% end %>

<%= link_to "一覧に戻る", fashions_path %>

app/views/fashions/news.html.erb
<h1>NEWS</h1>
<% @fashion.each do |t| %>
    <% if t.genre == "news" %>  
    <p>タイトル:<%= t.title %></p>
    <p>ジャンル:<%= t.genre %></p>
    <p>内容:<%= t.about %></p>
    <p>画像:<%= image_tag t.image_url, size: "250x200" if t.image? %></p>
    <p>投稿日:<%= t.created_at %></p>
    <% end %>
  <% end %>

  <%= link_to "一覧に戻る", fashions_path %>

app/views/fashions/others.html.erb
<h1>OTHERS</h1>
<% @fashion.each do |t| %>
    <% if t.genre == "others" %>  
    <p>タイトル:<%= t.title %></p>
    <p>ジャンル:<%= t.genre %></p>
    <p>内容:<%= t.about %></p>
    <p>画像:<%= image_tag t.image_url, size: "250x200" if t.image? %></p>
    <p>投稿日:<%= t.created_at %></p>
    <% end %>
  <% end %>

  <%= link_to "一覧に戻る", fashions_path %>

app/views/fashions/show.html.erb
<h1>Now Trend</h1>
<h3>Fashion詳細</h3>
<%= image_tag @fashion.image_url, size: "400x300" if @fashion.image? %>

<div class="fashion">
  <p><%= @fashion.title %></p>
  <p><%= @fashion.genre %></p>
  <p><%= @fashion.about %></p>
  <p><%= @fashion.image %></p>
  <p><%= @fashion.created_at %></p>
   <% if user_signed_in? %>
    <% if current_user.already_liked?(@fashion) %>
     <%= link_to fashion_like_path(@fashion), method: :delete do %>
      <i class="fas fa-heart"></i><%= @fashion.likes.count %>
     <% end %>
  <% else %>
    <%= link_to fashion_likes_path(@fashion), method: :post do %>
      <i class="far fa-heart"></i><%= @fashion.likes.count %>
    <% end %>
  <% end %>
<% else %>
  <i class="far fa-heart"></i><%= @fashion.likes.count %>
<% end %>
<%= link_to "編集する", edit_fashion_path(@fashion.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @fashion.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@fashion, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "一覧に戻る", fashions_path %>

app/views/fashions/things.html.erb
<h1>THINGS</h1>
<% @fashion.each do |t| %>
    <% if t.genre == "things" %> 
    <p>タイトル:<%= t.title %></p>
    <p>ジャンル:<%= t.genre %></p>
    <p>内容:<%= t.about %></p>
    <p>画像:<%= image_tag t.image_url, size: "250x200" if t.image? %></p>
    <p>投稿日:<%= t.created_at %></p>
    <% end %>
  <% end %>

  <%= link_to "一覧に戻る", fashions_path %>

app/views/fashions/word.html.erb
<h1>WORD</h1>
<% @fashion.each do |t| %>
    <% if t.genre == "word" %>  
    <p>タイトル:<%= t.title %></p>
    <p>ジャンル:<%= t.genre %></p>
    <p>内容:<%= t.about %></p>
    <p>画像:<%= image_tag t.image_url, size: "250x200" if t.image? %></p>
    <p>投稿日:<%= t.created_at %></p>
    <% end %>
  <% end %>

  <%= link_to "一覧に戻る", fashions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notefashion</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/8cb10e8cee.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<%= link_to "ログイン", fashions_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>